# Makefile for the openflexure block stage
# Generated by generate_makefile.py
.PHONY: all cleanstl

SOURCE = openscad
OUTPUT = builds

BODIES := main_body_micromanipulator_2mm main_body_fibre_stage_1mm
BASES := base_micromanipulator_2mm base_fibre_stage_1mm
TOOLS := actuator_assembly_tools
ACCESSORIES := accessories/LED_to_top_plate accessories/rms_to_top_plate accessories/CPS532_to_top_plate accessories/microscope_module
COMMONPARTS := gears small_gears moving_platform
ALLPARTS := $(COMMONPARTS) $(TOOLS) $(BODIES) $(BASES) $(ACCESSORIES)
ALLSTLFILES := $(ALLPARTS:%=$(OUTPUT)/%.stl)

parameters_file := $(SOURCE)/parameters.scad
utilities_file := $(SOURCE)/utilities.scad
all_deps := $(parameters_file) $(utilities_file)             #All targets depend on these

all: $(ALLSTLFILES)

cleanstl:
	rm $(STLFILES)

#parameter and utilities files affect everything
$(OUTPUT)/%.stl: $(all_deps)

main_body_dep_names := compact_nut_seat fibre_stage_three_legs
main_body_deps := $(main_body_dep_names:%=$(SOURCE)/%.scad)
$(OUTPUT)/main_body_micromanipulator_2mm.stl: $(SOURCE)/main_body.scad $(main_body_deps)
	openscad -o $@ -D 'xy_lever=20' -D 'z_lever=20' -D 'beam_height=85' -D 'fixed_stage=false' -D 'breadboard_lugs="diagonal"' $<

 
$(OUTPUT)/base_micromanipulator_2mm.stl: $(SOURCE)/base.scad $(main_body_deps)
	openscad -o $@ -D 'xy_lever=20' -D 'z_lever=20' -D 'beam_height=85' -D 'fixed_stage=false' -D 'breadboard_lugs="diagonal"' $<

$(OUTPUT)/main_body_fibre_stage_1mm.stl: $(SOURCE)/main_body.scad $(main_body_deps)
	openscad -o $@ -D 'xy_lever=10' -D 'z_lever=10' -D 'beam_height=75' -D 'fixed_stage=true' -D 'breadboard_lugs="diagonal"' $<

 
$(OUTPUT)/base_fibre_stage_1mm.stl: $(SOURCE)/base.scad $(main_body_deps)
	openscad -o $@ -D 'xy_lever=10' -D 'z_lever=10' -D 'beam_height=75' -D 'fixed_stage=true' -D 'breadboard_lugs="diagonal"' $<



$(OUTPUT)/accessories/LED_to_top_plate.stl: $(SOURCE)/accessories/LED_to_top_plate.scad
	openscad -o $@ $<

$(OUTPUT)/accessories/rms_to_top_plate.stl: $(SOURCE)/accessories/rms_to_top_plate.scad
	openscad -o $@ $<

$(OUTPUT)/accessories/CPS532_to_top_plate.stl: $(SOURCE)/accessories/CPS532_to_top_plate.scad
	openscad -o $@ $<

$(OUTPUT)/accessories/microscope_module.stl: $(SOURCE)/accessories/microscope_module.scad
	openscad -o $@ $<


$(OUTPUT)/%.stl: $(SOURCE)/%.scad $(all_deps)
	openscad -o $@ $<


